from rest_framework import serializers
from .models import Camera
from django.contrib.auth.password_validation import validate_password
from rest_framework_simplejwt.tokens import RefreshToken
from .models import User
from .models import SafetyViolation
from .models import InjuryAlert
from .models import InactivityAlert

class CameraSerializer(serializers.ModelSerializer): 
    """
    Used for CREATE and full GET responses.
    Serializes all Camera fields.
    'camera_id' and 'project' are read-only in the response
    """
    class Meta:
        model = Camera
        fields = [
            'camera_id',
            'project',
            'location_description',
            'stream_url',
        ]
        read_only_fields = ['camera_id']


class CameraUpdateSerializer(serializers.Serializer):
    """
    Used only for partial updates Instead of sending the whole object, the client sends:
    - camera_id
    - field  (the field name to update)
    - value  (the new value)
    """
    UPDATABLE_FIELDS = ['location_description', 'stream_url']

    field = serializers.ChoiceField(choices=UPDATABLE_FIELDS)
    value = serializers.CharField()

    def validate_value(self, value):  
        # If the field being updated is'stream_url',we validate it's actually a valid URL.

        field = self.initial_data.get('field')
        if field == 'stream_url':
            url_validator = serializers.URLField()
            try:
                url_validator.run_validation(value)
            except serializers.ValidationError:
                raise serializers.ValidationError("A valid URL is required for stream_url.")
        return value
    

class UserRegistrationSerializer(serializers.ModelSerializer):
    """
    Handles new user registration
    - password is write_only so it never appears in responses
    - we validate password strength using Django's built-in validators
    - role must be one of: engineer, owner
    """
    password = serializers.CharField(write_only=True, validators=[validate_password])

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'role']

    def create(self, validated_data):
        # Use create_user so Django hashes the password, Never save plain text passwords
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data['email'],
            password=validated_data['password'],
            role=validated_data['role'],
        )
        return user


class UserLoginSerializer(serializers.Serializer):
    """
    Handles login by email + password.
    Returns JWT access and refresh tokens on success.
    """
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)

    def validate(self, data):
        email = data.get('email')
        password = data.get('password')

        # Find user by email
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise serializers.ValidationError("No account found with this email.")

        # Check password
        if not user.check_password(password):
            raise serializers.ValidationError("Incorrect password.")

        # Check account is active
        if not user.is_active:
            raise serializers.ValidationError("This account is inactive.")

        # Generate JWT tokens
        refresh = RefreshToken.for_user(user)

        return {
            "user_id": str(user.user_id),
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "access": str(refresh.access_token),
            "refresh": str(refresh),
        }
    

class SafetyViolationSerializer(serializers.ModelSerializer):
    
    # Used for CREATE and GET responses : 'violation_id' and 'created_at' are read-only, and they are auto-generated by the database  
    
    class Meta:
        model = SafetyViolation
        fields = [
            'violation_id',
            'project',
            'camera',
            'violation_type',
            'evidence_storage_key',
            'created_at',
        ]
        read_only_fields = ['violation_id', 'created_at']



class InjuryAlertSerializer(serializers.ModelSerializer):
    """
    Used for CREATE and GET responses.
    'alert_id' and 'created_at' are read-only — they are auto-generated by the database.
    """
    class Meta:
        model = InjuryAlert
        fields = [
            'alert_id',
            'project',
            'camera',
            'alert_type',
            'evidence_storage_key',
            'created_at',
        ]
        read_only_fields = ['alert_id', 'created_at']




class InactivityAlertSerializer(serializers.ModelSerializer):
    
    # Used for CREATE and GET responses.
    
    class Meta:
        model = InactivityAlert
        fields = [
            'alert_id',
            'project',
            'camera',
            'created_at',
        ]
        read_only_fields = ['alert_id', 'created_at']



from .models import ProjectMember, Project


class ProjectMemberSerializer(serializers.ModelSerializer):
    """
    Used for displaying project members.
    Shows full user details instead of just the UUID.
    """
    username = serializers.CharField(source='user.username', read_only=True)
    email = serializers.CharField(source='user.email', read_only=True)
    role = serializers.CharField(source='user.role', read_only=True)
    user_id = serializers.UUIDField(source='user.user_id', read_only=True)

    class Meta:
        model = ProjectMember
        fields = ['user_id', 'username', 'email', 'role']



from .models import DailyProgressUpdate


class DailyProgressUpdateSerializer(serializers.ModelSerializer):
    """
    Used for CREATE and GET responses.
    - 'update_id' is read-only — auto-generated
    - 'progress_percentage' must be between 0.00 and 100.00
    - 'details' is a JSONField — can store any extra data the AI sends
    for example: {"completed_floors": 3, "pending_tasks": ["roofing"]}
    - 'created_at' is the date of this progress snapshot
    """
    class Meta:
        model = DailyProgressUpdate
        fields = [
            'update_id',
            'project',
            'progress_percentage',
            'details',
            'created_at',
        ]
        read_only_fields = ['update_id']

    def validate_progress_percentage(self, value):
        """
        Make sure progress is between 0 and 100.
        Anything outside this range makes no sense.
        """
        if value < 0 or value > 100:
            raise serializers.ValidationError(
                "Progress percentage must be between 0 and 100."
            )
        return value




class ProjectJoinSerializer(serializers.Serializer):
    """
    Used for joining a project using a 6-character project code.
    The user sends only the project_code — backend finds the project
    and creates the ProjectMember record automatically.
    """
    project_code = serializers.CharField(max_length=6)

    def validate_project_code(self, value):
        """
        Check the project code actually exists in the database.
        If not, return a clear error message.
        """
        try:
            project = Project.objects.get(project_code=value.upper())
        except Project.DoesNotExist:
            raise serializers.ValidationError(
                "Invalid project code. No project found with this code."
            )
        return value.upper()

    def get_project(self, code):
        return Project.objects.get(project_code=code)
    


class FCMTokenSerializer(serializers.Serializer):
    """
    Used to store the user's FCM token for push notifications.
    The Flutter app sends this token after login so Django
    knows which device to send notifications to.
    """
    fcm_token = serializers.CharField(max_length=500)