from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from rest_framework_simplejwt.tokens import RefreshToken
from .models import Project
from .models import Camera
from .models import User
from .models import SafetyViolation
from .models import DailyProgressUpdate


class CameraSerializer(serializers.ModelSerializer): 
    """
    Used for CREATE and full GET responses.
    Serializes all Camera fields.
    'camera_id' and 'project' are read-only in the response
    """
    class Meta:
        model = Camera
        fields = [
            'camera_id',
            'project',
            'location_description',
            'stream_url',
        ]
        read_only_fields = ['camera_id']


class CameraUpdateSerializer(serializers.Serializer):
    """
    Used only for partial updates Instead of sending the whole object, the client sends:
    - camera_id
    - field  (the field name to update)
    - value  (the new value)
    """
    UPDATABLE_FIELDS = ['location_description', 'stream_url']

    field = serializers.ChoiceField(choices=UPDATABLE_FIELDS)
    value = serializers.CharField()

    def validate_value(self, value):  
        # If the field being updated is'stream_url',we validate it's actually a valid URL.

        field = self.initial_data.get('field')
        if field == 'stream_url':
            url_validator = serializers.URLField()
            try:
                url_validator.run_validation(value)
            except serializers.ValidationError:
                raise serializers.ValidationError("A valid URL is required for stream_url.")
        return value
    

class UserRegistrationSerializer(serializers.ModelSerializer):
    """
    Handles new user registration
    - password is write_only so it never appears in responses
    - we validate password strength using Django's built-in validators
    - role must be one of: engineer, owner
    """
    password = serializers.CharField(write_only=True, validators=[validate_password])

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'role']


    email = serializers.EmailField(required=True)
    password = serializers.CharField(write_only=True, validators=[validate_password])

    def create(self, validated_data):
        # Use create_user so Django hashes the password, Never save plain text passwords
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data['email'],
            password=validated_data['password'],
            role=validated_data['role'],
        )
        return user


class UserLoginSerializer(serializers.Serializer):
    """
    Handles login by email + password.
    Returns JWT access and refresh tokens on success.
    """
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)

    def validate(self, data):
        email = data.get('email')
        password = data.get('password')

        # Find user by email
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise serializers.ValidationError("No account found with this email.")

        # Check password
        if not user.check_password(password):
            raise serializers.ValidationError("Incorrect password.")

        # Check account is active
        if not user.is_active:
            raise serializers.ValidationError("This account is inactive.")

        # Generate JWT tokens
        refresh = RefreshToken.for_user(user)

        return {
            "user_id": str(user.user_id),
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "access": str(refresh.access_token),
            "refresh": str(refresh),
        }
    

class SafetyViolationSerializer(serializers.ModelSerializer):
    
    # Used for CREATE and GET responses : 'violation_id' and 'created_at' are read-only, and they are auto-generated by the database  
    
    class Meta:
        model = SafetyViolation
        fields = [
            'violation_id',
            'project',
            'camera',
            'violation_type',
            'evidence_storage_key',
            'created_at',
        ]
        read_only_fields = ['violation_id', 'created_at']


class ProjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = [
            'project_id',
            'project_name',
            'project_code',
            'location_address',
            'start_date',
            'structural_design_storage_key',
            'architectural_design_storage_key'
        ]
        
        read_only_fields = [
            'project_id',
            'project_code'
        ]
    
    updatable_fields = {
        'project_name',
        'location_address',
        'start_date',
        'structural_design_storage_key',
        'architectural_design_storage_key'
    }


class DailyProgressUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = DailyProgressUpdate

        fields = [
            'update_id',
            'project',
            'progress_percentage',
            'details',
            'created_at'
            ]
        
        read_only_fields = [
            'update_id',
            'created_at'
            ]
