# Generated by Django 6.0.3 on 2026-04-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.DeleteModel(
            name='DailyProgressUpdate',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
