# Generated by Django 6.0.3 on 2026-04-12 20:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(default=backend.models.generate_unique_project_code, max_length=6, unique=True),
        ),
    ]
