# Generated by Django 6.0.4 on 2026-05-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_dailyprogressupdate_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
