# Generated by Django 6.0.3 on 2026-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogressupdate',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
