# Generated by Django 6.0.3 on 2026-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_dailyprogressupdate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogressupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
