# Generated by Django 6.0.4 on 2026-04-26 15:46

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_dailyprogressupdate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogressupdate',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(default=backend.models.generate_unique_project_code, editable=False, max_length=6, unique=True),
        ),
    ]
